version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - npm run build     
artifacts:
  files:
    - '**/*'
  base-directory: build
