version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - aws s3 rm s3://react-gift-app.s3-website-us-west-2.amazonaws.com --recursive
      - aws s3 cp build s3://react-gift-app.s3-website-us-west-2.amazonaws.com --recursive --acl public-read

artifacts:
  files:
    build/**/*
